"""init

Revision ID: 18d3ec58e2a3
Revises: 
Create Date: 2026-05-21 12:07:58.433352

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '18d3ec58e2a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=300), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_deleted_at'), 'admin_users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_admin_users_telegram_id'), 'admin_users', ['telegram_id'], unique=True)
    op.create_table('directions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_uz', sa.String(length=200), nullable=False),
    sa.Column('name_ru', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_emoji', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directions_deleted_at'), 'directions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_directions_slug'), 'directions', ['slug'], unique=True)
    op.create_table('specialties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('name_uz', sa.String(length=200), nullable=False),
    sa.Column('name_ru', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['direction_id'], ['directions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specialties_deleted_at'), 'specialties', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_specialties_direction_id'), 'specialties', ['direction_id'], unique=False)
    op.create_index(op.f('ix_specialties_slug'), 'specialties', ['slug'], unique=True)
    op.create_table('position_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['direction_id'], ['directions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('direction_id', 'specialty_id', 'code', name='uq_code_per_specialty')
    )
    op.create_index('ix_position_code_lookup', 'position_codes', ['direction_id', 'specialty_id'], unique=False)
    op.create_index(op.f('ix_position_codes_code'), 'position_codes', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_position_codes_code'), table_name='position_codes')
    op.drop_index('ix_position_code_lookup', table_name='position_codes')
    op.drop_table('position_codes')
    op.drop_index(op.f('ix_specialties_slug'), table_name='specialties')
    op.drop_index(op.f('ix_specialties_direction_id'), table_name='specialties')
    op.drop_index(op.f('ix_specialties_deleted_at'), table_name='specialties')
    op.drop_table('specialties')
    op.drop_index(op.f('ix_directions_slug'), table_name='directions')
    op.drop_index(op.f('ix_directions_deleted_at'), table_name='directions')
    op.drop_table('directions')
    op.drop_index(op.f('ix_admin_users_telegram_id'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_deleted_at'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
